### ISSUE TITLE
Where is the embedded controls?

### ISSUE THREAD

**Issue by desbest** [bamdadsabbagh/screwmycode-in--extension#214]
Where are the embedded controls for me to change the pitch of songs on youtube without me having to click the Firefox toolbar button?

**Comment by bamdadsabbagh** [comment]
Hi @desbest,

Thanks for posting your issue and sorry for the delay in my answer.

The embedded controls are located in the player bar.

![image](https://user-images.githubusercontent.com/17913954/188645005-2239226f-f9ea-4fc0-be26-3bc2c1684820.png)

Please let me know if you need any further help.
