### ISSUE TITLE
Stops working whenever the quality automatically changes

### ISSUE THREAD

**Issue by gameshowrecaps** [bamdadsabbagh/screwmycode-in--extension#270]
I have noticed whenever the quality changes automatically while skipping through a video or when it buffers for a while, the pitch changer stops working and goes back to the normal pitch (meaning when I put the pitch up or down, the pitch does not change). This means I have to refresh the page to get the pitch changer working again.

**Comment by bamdadsabbagh** [comment]
Hi,

Thanks for creating this issue. I have a couple of questions that will help me reproduce this.

- Do you observe this behaviour on both Firefox and Chrome?
- Does it happen when you manually change the bitrate too?

Thanks for your help!

**Comment by gameshowrecaps** [comment]
> Hi,
> 
> Thanks for creating this issue. I have a couple of questions that will help me reproduce this.
> 
>     * Do you observe this behaviour on both Firefox and Chrome?
> 
>     * Does it happen when you manually change the bitrate too?
> 
> 
> Thanks for your help!

1. I can confirm this on Firefox. I will update whenever something happens on Chrome.
2. On Chrome, this bug does not happen when I change the bitrate.

**Comment by bamdadsabbagh** [comment]
Thanks for your answers.

Are you running other YouTube altering web extensions? Because I can not reproduce with my Firefox.

**Comment by gameshowrecaps** [comment]
> Thanks for your answers.
> 
> Are you running other YouTube altering web extensions? Because I can not reproduce with my Firefox.

Many.

YouTube Redux + Return YouTube Dislike + Enhancer for YouTube, and a code on Stylus.

**Comment by gameshowrecaps** [comment]
It was the YouTube Auto HD extension this whole time, just went through a long buffer and the extension still worked. I'm closing this as I think I fixed it.

**Comment by bamdadsabbagh** [comment]
Glad you got it sorted. Thanks for taking the time investigating.
